### ISSUE TITLE
Generate wrong calcChain.xml

### ISSUE THREAD

**Issue by gronerup** [cuba-platform/yarg#26] opened 2017-09-01 08:14 UTC
Hello! I can generate the report without error with Yarg. However, when I open the output xlsx file, it errors out saying there problem in the content and asking me if I want to correct it or not. If I click yes, it prompts message: Removed Records: Formula from /xl/calcChain.xml part (

Calculation properties). After report becomes good. Please help me to generate report  correctly in the beginning.
[CodeReport.txt](https://github.com/cuba-platform/yarg/files/1269593/CodeReport.txt)
[Report.xlsx](https://github.com/cuba-platform/yarg/files/1269560/Report.xlsx)

**Comment by andreysubbotin** [comment] 2017-09-01 08:30
Hi,
What is the YARG version do you use?

**Comment by gronerup** [comment] 2017-09-01 09:14
i  have 2.0.4

**Comment by ODE-SA** [comment] 2017-10-03 16:35
We encountered the same issue. It is fixed in the pull request from grebesche (https://github.com/cuba-platform/yarg/pull/27)

The issue is due to the fact that Yarg sets the i value to 1 for the first formula, which makes all the subsequent formulas to be on the 1st sheet that was added to the workbook (not necessarily Sheet1).

The issue is triggered when any formula is anywhere but on the 1st sheet that was added to the workbook.

@gronerup: would you be able to use the fix from that pull request and let us know if it fixes your issue?

**Comment by andreysubbotin** [comment] 2017-10-11 14:47
Fixed by grebesche (#27)

**Closed by andreysubbotin** 2017-10-11 14:47 UTC
Labels: bug

**Comment by kkorada** [comment] 2018-07-05 08:59
i am getting same issue when i copy the formula from one cell to another cell
