### ISSUE TITLE
Remove BootstrapException in BootstrapConnector.connect

### ISSUE THREAD

**Issue by kjordan2001** [cuba-platform/yarg#15] opened 2016-12-13 22:58 UTC
Can this be changed to throw the original exception?  There are a variety of things that can happen in the original exception that are hidden by wrapping it in a BootstrapException since the original isn't added to the stacktrace, instead it's in a separate getter that you'd have to get by going through the exception stack since it's wrapped again before we get it into an OpenOfficeException.  I ask this because it was difficult for me to tell what was going on with a problem I had using yarg in an updated EC2 Beanstalk environment where a permission change in the tomcat home directory prevented it from making a .openoffice directory and it was immediately clear when I did my own version of BootstrapConnector that returned the original error.

**Comment by tinhol** [comment] 2016-12-14 09:00
Hello.

Do you mean the following part of code?
`for (int i = 0;; ++i) {
                try {
                    xContext = getRemoteContext(xUrlResolver);
                    break;
                } catch ( NoConnectException ex ) {
                    // Wait 500 ms, then try to connect again, but do not wait
                    // longer than 5 sec total:
                    if (i == 10) {
                        throw new BootstrapException(ex.toString());
                    }
                    Thread.sleep(500);
                }
            }`

**Comment by kjordan2001** [comment] 2016-12-14 17:40
No, more like in pull request #16 that I just added.  Although avoiding that Exception type anywhere would be a better way to go since it covers up the underlying exception.

**Comment by tinhol** [comment] 2016-12-15 08:30
Well, I'm not sure it's a good idea, because `throws Throwable` just does not mean anything certain, and does not help client to handle it at all.
Wouldn't it be sufficient if you get the original exception wrapped by BootstrapException (`new BootstrapException(e)`) instead of creating BootstrapException with source exception's text (`new BootstrapException(ex.toString())`)?

**Comment by kjordan2001** [comment] 2017-05-12 21:07
That'd only be slightly better.  Unfortunately that doesn't act like most other Exceptions do when you pass in another Exception as the constructor parameter.  That only allows you to get it from getTargetException.  It seems like it'd be better to have another exception type rather than using one from the OpenOffice API.

**Comment by tinhol** [comment] 2017-08-25 15:52
Hello. 

We will remove the BootstrapException from BootstrapConnector implementations in future releases.

**Comment by tinhol** [comment] 2018-01-18 08:40
Hello.

The issue is resolved in master branch.

**Closed by tinhol** 2018-01-18 08:40 UTC
Labels: enhancement
